### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by Lolic3**
He creado un pull request template para que sirva de guia siempre que hagamos un pull request.

### CODE REVIEW

**Review by JJ — COMMENTED** [review]
All of a sudden everyone is speaking English. Apparently, since we have started an Erasmus program, is the right thing to do... 🏴󠁧󠁢󠁥󠁮󠁧󠁿 
Are you sure that is the right directory?

**Comment by Lolic3** [comment]
I'm actually not sure of anything anymore haha, I'm gonna change directory to docs and also I'm gonna introduce the PR into the Nivel-2 branch.

**Review by JJ — CHANGES_REQUESTED** [review]
Again, [are you sure](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)?

**Review by JJ — APPROVED** [review]
A la tercera va la vencida.

**Comment by Lolic3** [comment]
Now I need to ask why... Why is that one the proper directory?

**Comment by lugaresdev** [comment]
Estoy de acuerdo @Lolic3 
image

**Review by lugaresdev — APPROVED** [review]

**Comment by JJ** [comment]
> Now I need to ask why... Why is that one the proper directory?

RTFM... https://docs.github.com/assets/cb-70797/mw-1440/images/help/repository/add-file-buttons.webp

**Pull request merged**
